"""add agents, mcp servers, and their domain/tool links

Revision ID: 253d492b3b04
Revises: e717eccd3cad
Create Date: 2026-08-06 00:54:46.134159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '253d492b3b04'
down_revision: Union[str, Sequence[str], None] = 'e717eccd3cad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # NOTE: autogenerate also proposed dropping ix_document_chunks_document_id,
    # ix_document_chunks_embedding_hnsw and ix_documents_domain_id — the same
    # known false positive noted in e272b45380b3/e717eccd3cad (see
    # .claude/skills/db-migration/SKILL.md): those indexes are created via
    # raw op.execute()/op.create_index() in 542eb8b7605b and aren't
    # represented in SQLAlchemy model metadata. Intentionally not touching
    # them here.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('api_key', sa.String(length=1000), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('system_prompt_template', sa.String(length=255), nullable=False),
    sa.Column('max_iterations', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('top_p', sa.Float(), nullable=True),
    sa.Column('enable_knowledge_search', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mcp_servers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('transport', sa.String(length=16), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('agent_mcp_servers',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('mcp_server_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mcp_server_id'], ['mcp_servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'mcp_server_id')
    )
    op.create_table('domain_agents',
    sa.Column('domain_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('domain_id', 'agent_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('domain_agents')
    op.drop_table('agent_mcp_servers')
    op.drop_table('mcp_servers')
    op.drop_table('agents')
    # ### end Alembic commands ###
