"""add request_logs table

Revision ID: 50f7ec41ac19
Revises: 545353cf397f
Create Date: 2026-08-10 22:58:52.723506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50f7ec41ac19'
down_revision: Union[str, Sequence[str], None] = '545353cf397f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # NOTE: autogenerate also proposed dropping ix_document_chunks_document_id,
    # ix_document_chunks_embedding_hnsw and ix_documents_domain_id — the same
    # known false positive as prior migrations (see .claude/skills/db-migration/
    # SKILL.md): those indexes are created via raw op.execute()/
    # op.create_index() in 542eb8b7605b and aren't represented in SQLAlchemy
    # model metadata, so autogenerate's DB-vs-metadata diff mistakes them for
    # removed indexes. Intentionally not touching them here.
    op.create_table('request_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('stopped_on', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('success', 'error')", name='ck_request_logs_status'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_request_logs_agent_created', 'request_logs', ['agent_id', 'created_at'], unique=False)
    op.create_index('ix_request_logs_api_key_created', 'request_logs', ['api_key_id', 'created_at'], unique=False)
    op.create_index('ix_request_logs_created_at', 'request_logs', ['created_at'], unique=False)
    op.create_index('ix_request_logs_model_name', 'request_logs', ['model_name'], unique=False)
    op.create_index('ix_request_logs_status', 'request_logs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_request_logs_status', table_name='request_logs')
    op.drop_index('ix_request_logs_model_name', table_name='request_logs')
    op.drop_index('ix_request_logs_created_at', table_name='request_logs')
    op.drop_index('ix_request_logs_api_key_created', table_name='request_logs')
    op.drop_index('ix_request_logs_agent_created', table_name='request_logs')
    op.drop_table('request_logs')
    # ### end Alembic commands ###
