"""chat messages agent scoped

Revision ID: 545353cf397f
Revises: e28f863c84bc
Create Date: 2026-08-06 14:23:21.659464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '545353cf397f'
down_revision: Union[str, Sequence[str], None] = 'e28f863c84bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # NOTE: autogenerate also proposed dropping ix_document_chunks_document_id,
    # ix_document_chunks_embedding_hnsw and ix_documents_domain_id — the same
    # known false positive noted in e272b45380b3/e717eccd3cad/253d492b3b04/
    # e28f863c84bc (see .claude/skills/db-migration/SKILL.md): those indexes
    # are created via raw op.execute()/op.create_index() in 542eb8b7605b and
    # aren't represented in SQLAlchemy model metadata. Intentionally not
    # touching them here.
    #
    # chat_messages is being re-scoped from (domain_id, session_id) to
    # (agent_id, session_id). There is no data-preserving mapping from a
    # domain to an agent (not 1:1), so this is a dev-only, destructive
    # rename — truncate first.
    op.execute("TRUNCATE TABLE chat_messages")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('agent_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_chat_messages_domain_session_created'), table_name='chat_messages')
    op.create_index('ix_chat_messages_agent_session_created', 'chat_messages', ['agent_id', 'session_id', 'created_at'], unique=False)
    op.drop_constraint(op.f('chat_messages_domain_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chat_messages', 'domain_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Symmetric with upgrade(): going backward has the same data-loss
    # reality (no mapping from agent_id back to a single domain_id).
    op.execute("TRUNCATE TABLE chat_messages")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('domain_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_domain_id_fkey'), 'chat_messages', 'domains', ['domain_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_chat_messages_agent_session_created', table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_domain_session_created'), 'chat_messages', ['domain_id', 'session_id', 'created_at'], unique=False)
    op.drop_column('chat_messages', 'agent_id')
    # ### end Alembic commands ###
