"""agent free-text system prompt

Revision ID: e28f863c84bc
Revises: 253d492b3b04
Create Date: 2026-08-06 08:27:23.002523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e28f863c84bc'
down_revision: Union[str, Sequence[str], None] = '253d492b3b04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # NOTE: autogenerate also proposed dropping ix_document_chunks_document_id,
    # ix_document_chunks_embedding_hnsw and ix_documents_domain_id — the same
    # known false positive noted in e272b45380b3/e717eccd3cad/253d492b3b04
    # (see .claude/skills/db-migration/SKILL.md): those indexes are created
    # via raw op.execute()/op.create_index() in 542eb8b7605b and aren't
    # represented in SQLAlchemy model metadata. Intentionally not touching
    # them here.
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('system_prompt', sa.Text(), nullable=True))
    op.drop_column('agents', 'system_prompt_template')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('system_prompt_template', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('agents', 'system_prompt')
    # ### end Alembic commands ###
