from __future__ import annotations

import uuid

import pytest

from app.channels.base import ChannelParseError
from app.channels.generic import GenericAdapter


@pytest.fixture
def adapter() -> GenericAdapter:
    return GenericAdapter()


async def test_parse_incoming_happy_path(adapter: GenericAdapter) -> None:
    payload = {
        "agent_id": "a1",
        "session_id": "s1",
        "message": "hello",
        "metadata": {"foo": "bar"},
    }
    message = await adapter.parse_incoming(payload, headers={})
    assert message.agent_id == "a1"
    assert message.session_id == "s1"
    assert message.text == "hello"
    assert message.metadata == {"foo": "bar"}


async def test_parse_incoming_session_id_autogenerated(adapter: GenericAdapter) -> None:
    payload = {"agent_id": "a1", "message": "hi"}
    message = await adapter.parse_incoming(payload, headers={})
    assert message.session_id
    # must be a valid uuid4 string
    uuid.UUID(message.session_id)


async def test_parse_incoming_missing_agent_id_raises(adapter: GenericAdapter) -> None:
    with pytest.raises(ChannelParseError):
        await adapter.parse_incoming({"message": "hi"}, headers={})


async def test_parse_incoming_missing_message_raises(adapter: GenericAdapter) -> None:
    with pytest.raises(ChannelParseError):
        await adapter.parse_incoming({"agent_id": "a1"}, headers={})


async def test_parse_incoming_invalid_metadata_raises(adapter: GenericAdapter) -> None:
    with pytest.raises(ChannelParseError):
        await adapter.parse_incoming(
            {"agent_id": "a1", "message": "hi", "metadata": "not-a-dict"}, headers={}
        )


async def test_platform_slug(adapter: GenericAdapter) -> None:
    assert adapter.platform == "generic"


async def test_send_response_default_noop(adapter: GenericAdapter) -> None:
    from app.channels.base import OutgoingMessage

    result = await adapter.send_response(OutgoingMessage(session_id="s1", text="hi"))
    assert result is None
